object Modules {
    const val app = ":app"
    const val base = ":base"
    const val core = ":core"
    const val navigation = ":navigation"
    const val cache = ":data:cache"
    const val network = ":data:network"
    const val repositoryImpl = ":data:repository-impl"
    const val repository = ":domain:repository"
    const val safe = ":safe"
    const val emoji = ":emoji"
    const val cookieJar = ":cookie-jar"
    const val entity = ":domain:entity"
    const val countryPicker = ":country-picker"
    const val signin = ":features:signin"
    const val signup = ":features:signup"
    const val conversation = ":features:conversation"
    const val androidCore = ":androidCore"
    const val db = ":data:db"
    const val mvi = ":mvi"
    const val hiltCore = ":hilt-core"
}
