object Modules {
    const val app = ":app"
    const val commonUi = ":common-ui"
    const val core = ":core"
    const val navigation = ":navigation"
    const val cache = ":cache"
    const val safe = ":safe"
    const val emoji = ":emoji"
    const val cookieJar = ":cookie-jar"
    const val domain = ":domain"
    const val countryPicker = ":country-picker"
    const val login = ":features:login"
    const val chat = ":features:chat"
    const val workspaceSelect = ":features:workspace-select"
    const val workspaceCreate = ":features:workspace-create"
    const val conversation = ":features:conversations"
    const val splash = ":features:splash"
    const val signup = ":features:signup"
    const val mvi = ":mvi"
    const val data = ":data"
    const val coreAndroid = ":core-android"
    const val fileManager = ":file-manager"
}
