object Modules {
    const val app = ":app"
    const val base = ":base"
    const val core = ":core"
    const val navigation = ":navigation"
    const val cache = ":cache"
    const val safe = ":safe"
    const val emoji = ":emoji"
    const val cookieJar = ":cookie-jar"
    const val domain = ":domain"
    const val countryPicker = ":country-picker"
    const val login = ":features:login"
    const val profile = ":features:profile"
    const val conversation = ":features:conversation"
    const val mvi = ":mvi"
    const val data = ":data"
}
